## Exercise 3.5

In [1]:
import numpy as np

B = np.array([[0, 1, -3, -1],
              [-1, -3, 4, -3],
              [2, 1, 1, 5],
              [0, -1, 2, 0],
              [2, 2, 1, 7]])

#but this is not a basis!

B = B[:, :-1]

x = np.array([-1,-9, -1, 4, 1])
print(B)
print(x)

[[ 0  1 -3]
 [-1 -3  4]
 [ 2  1  1]
 [ 0 -1  2]
 [ 2  2  1]]
[-1 -9 -1  4  1]


In [2]:
BtB = B.T @ B
print(BtB)
#print(np.linalg.matrix_rank(BtB))
inv = np.linalg.inv(BtB)
#inv = np.linalg.pinv(B) (alternative method)
print(inv)
print(inv@BtB)

[[  9   9   0]
 [  9  16 -14]
 [  0 -14  31]]
[[ 1.58730159 -1.47619048 -0.66666667]
 [-1.47619048  1.47619048  0.66666667]
 [-0.66666667  0.66666667  0.33333333]]
[[ 1.00000000e+00 -6.66133815e-16  2.10942375e-15]
 [-4.44089210e-16  1.00000000e+00  1.33226763e-15]
 [-3.33066907e-16 -3.33066907e-16  1.00000000e+00]]


In [3]:
coeff = inv @ B.T @ x
print(coeff)
proj = B @ coeff
print(proj)

[-3.  4.  1.]
[ 1. -5. -1. -2.  3.]


## Exercise 3.6
### Part A

First of all, let's define the basis and the inner product operation.

In [8]:
A = np.array([
    [2, 1, 0],
    [1, 2, -1],
    [0, -1, 2]
], dtype=np.int8)

B = np.array([
    [1, 0],
    [0, 0],
    [0, 1]
], np.int8)

def inn_prod(x, y):
    return x.T @ A @ y

e2 = np.array([0, 1, 0], np.int8)

Let's find the coordinates of the projection:

In [12]:
lambda_1 = inn_prod(e2, B[:, :1])/inn_prod(B[:, :1], B[:, :1])
lambda_1 = np.ndarray.item(lambda_1)
lambda_2 = inn_prod(e2, B[:, 1:])/inn_prod(B[:, 1:], B[:, 1:])
lambda_2 = np.ndarray.item(lambda_2)
print(lambda_1, lambda_2)

0.5 -0.5


Let's find the proper vector projection:

In [18]:
proj = lambda_1*B[:, :1] + lambda_2*B[:, 1:]
proj = proj.reshape(3)
print(proj)

[ 0.5  0.  -0.5]


### Part B

Let's compute the distance $d(e_2, U)$:

In [21]:
np.sqrt(inn_prod(e2 - proj, e2 - proj))

1.0