### Ex. 3.5

In [18]:
import numpy as np

B = np.array([[0, 1, -3, -1],
              [-1, -3, 4, -3],
              [2, 1, 1, 5],
              [0, -1, 2, 0],
              [2, 2, 1, 7]])

#but this is not a basis!

B = B[:, :-1]

x = np.array([-1,-9, -1, 4, 1])
print(B)
print(x)

[[ 0  1 -3]
 [-1 -3  4]
 [ 2  1  1]
 [ 0 -1  2]
 [ 2  2  1]]
[-1 -9 -1  4  1]


In [22]:
BtB = B.T @ B
print(BtB)
#print(np.linalg.matrix_rank(BtB))
inv = np.linalg.inv(BtB)
#inv = np.linalg.pinv(B) (alternative method)
print(inv)
print(inv@BtB)

[[  9   9   0]
 [  9  16 -14]
 [  0 -14  31]]
[[ 1.58730159 -1.47619048 -0.66666667]
 [-1.47619048  1.47619048  0.66666667]
 [-0.66666667  0.66666667  0.33333333]]
[[ 1.00000000e+00 -6.66133815e-16  2.10942375e-15]
 [-4.44089210e-16  1.00000000e+00  1.33226763e-15]
 [-3.33066907e-16 -3.33066907e-16  1.00000000e+00]]


In [21]:
coeff = inv @ B.T @ x
print(coeff)
proj = B @ coeff
print(proj)

[-3.  4.  1.]
[ 1. -5. -1. -2.  3.]
