## Exercise 8

Find the SVD of the matrix $A$.

In [186]:
import numpy as np

a = np.array([
    [3, 2, 2],
    [2, 3, -2]
], np.int8)

The first thing to do is to find the eigenvalue decomposition of $A^TA$.

In [187]:
ata = a.T @ a

eigenvalues_ata, v = np.linalg.eig(ata)
print(v)

[[-7.07106781e-01 -6.66666667e-01  2.35702260e-01]
 [-7.07106781e-01  6.66666667e-01 -2.35702260e-01]
 [-4.55680392e-17  3.33333333e-01  9.42809042e-01]]


Now, we can write the matrix $\Sigma$ and the matrix $V$, and calculate the matrix $U$:

In [188]:
partial_sigma = np.diag(np.sqrt(eigenvalues_ata[eigenvalues_ata > 1e-05]))
if a.shape[0]>a.shape[1]:
    sigma = np.pad(partial_sigma, pad_width= ((0, a.shape[0]-a.shape[1]), (0, 0)), constant_values=(0))
else:
    sigma = np.pad(partial_sigma, pad_width= ((0, 0), (0, a.shape[1]-a.shape[0])), constant_values=(0))

coefficients = np.diag(np.sqrt(1/eigenvalues_ata[eigenvalues_ata > 1e-05]))
u = a @ v[:, eigenvalues_ata > 1e-05] @ coefficients
print("U: \n", np.round(u, 3))
print("Sigma: \n", sigma)
#v[:, 1], v[:, 2] = v[:, 2], v[:, 1]
print("V: \n", np.round(v, 3))

U: 
 [[-0.707  0.707]
 [-0.707 -0.707]]
Sigma: 
 [[5. 0. 0.]
 [0. 3. 0.]]
V: 
 [[-0.707 -0.667  0.236]
 [-0.707  0.667 -0.236]
 [-0.     0.333  0.943]]


And now, the final check:

In [189]:
print(a)
print(np.around(u @ sigma @ v.T, 3))

[[ 3  2  2]
 [ 2  3 -2]]
[[ 1.086  3.914  0.707]
 [ 3.914  1.086 -0.707]]


In [190]:
#Debugging
A = np.array([
    [1, 0, 1],
    [-2, 1, 0]
], np.int8)

V = np.array([
    [5/np.sqrt(30), 0, -1/np.sqrt(6)],
    [-2/np.sqrt(30), 1/np.sqrt(5), -2/np.sqrt(6)],
    [1/np.sqrt(30), 2/np.sqrt(5), 1/np.sqrt(6)]
], np.float64)

eig = np.array([6, 1, 0], np.int8)

print(np.around(A @ V[:, eig>0] @ np.diag(np.sqrt(1/eig[eig > 0])), 3))

[[ 0.447  0.894]
 [-0.894  0.447]]


## Exercise 9

Find the SVD of the matrix $A$.

In [191]:
import numpy as np

a = np.array([
    [2, 2],
    [-1, 1]
], np.int8)

The first thing to do is to find the eigenvalue decomposition of $A^TA$.

In [192]:
ata = a.T @ a

eigenvalues_ata, v = np.linalg.eig(ata)
print(v)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


Now, we can write the matrix $\Sigma$ and the matrix $V$, and calculate the matrix $U$:

In [193]:
partial_sigma = np.diag(np.sqrt(eigenvalues_ata[eigenvalues_ata > 1e-05]))
if a.shape[0]>a.shape[1]:
    sigma = np.pad(partial_sigma, pad_width= ((0, a.shape[0]-a.shape[1]), (0, 0)), constant_values=(0))
else:
    sigma = np.pad(partial_sigma, pad_width= ((0, 0), (0, a.shape[1]-a.shape[0])), constant_values=(0))

coefficients = np.diag(np.sqrt(1/eigenvalues_ata[eigenvalues_ata > 1e-05]))
u = a @ v[:, eigenvalues_ata > 1e-05] @ coefficients
print("U: \n", np.round(u, 3))
print("Sigma: \n", sigma)
#v[:, 1], v[:, 2] = v[:, 2], v[:, 1]
print("V: \n", np.round(v, 3))

U: 
 [[ 1. -0.]
 [ 0.  1.]]
Sigma: 
 [[2.82842712 0.        ]
 [0.         1.41421356]]
V: 
 [[ 0.707 -0.707]
 [ 0.707  0.707]]


And now, the final check:

In [194]:
print(a)
print(np.around(u @ sigma @ v.T, 3))

[[ 2  2]
 [-1  1]]
[[ 2.  2.]
 [-1.  1.]]
