## Exercise 8

Find the SVD of the matrix $A$.

In [4]:
import numpy as np

A = np.array([
    [3, 2, 2],
    [2, 3, -2]
], np.int8)

The first thing to do is to find the eigenvalue decomposition of $A^TA$.

In [5]:
ata = A.T @ A

eigenvalues_ata, eigenvectors_ata = np.linalg.eig(ata)
print(eigenvalues_ata)
print(eigenvectors_ata)

[2.5000000e+01 5.0324328e-15 9.0000000e+00]
[[-7.07106781e-01 -6.66666667e-01  2.35702260e-01]
 [-7.07106781e-01  6.66666667e-01 -2.35702260e-01]
 [-4.55680392e-17  3.33333333e-01  9.42809042e-01]]


Now, we can write the matrix $\Sigma$ and the matrix $V$, and calculate the matrix $U$:

In [16]:
sigma = np.diag(np.sqrt(eigenvalues_ata))
v = eigenvectors_ata
coefficients = np.diag(np.sqrt(1/eigenvalues_ata))
#print(coefficients)
u = A @ v @ coefficients
print("U: \n",u)
print("Sigma: \n",sigma)
print("V: \n",v)

U: 
 [[-7.07106781e-01  1.56502485e-09  7.07106781e-01]
 [-7.07106781e-01 -1.09551739e-08 -7.07106781e-01]]
Sigma: 
 [[5.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 7.0939642e-08 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 3.0000000e+00]]
V: 
 [[-7.07106781e-01 -6.66666667e-01  2.35702260e-01]
 [-7.07106781e-01  6.66666667e-01 -2.35702260e-01]
 [-4.55680392e-17  3.33333333e-01  9.42809042e-01]]


And now, the final check:

In [13]:
print(A)
print(np.around(u @ sigma @ v, 3))

[[ 3  2  2]
 [ 2  3 -2]]
[[ 2.5    3.064  1.167]
 [ 2.5    1.65  -2.833]]
