# Intro to OpenCV

OpenCV images are NumPy arrays, and can be manipulated as such.

## Manipulating existing images

In [1]:
import cv2

img = cv2.imread("samples/text.png")  #setting this to 0 gives a greyscale image, -1 to colour, -1 to transparency and so on
print(f"Width: {img.shape[1]} pixels")
print(f"Heigth: {img.shape[0]} pixels")
print(f"Shape: {img.shape}")

Width: 1110 pixels
Heigth: 220 pixels
Shape: (220, 1110, 3)


In [2]:
cv2.imshow("ciao", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

It is possible to change the format of the image just by rewriting it:

In [3]:
'''
cv2.imwrite("wtf.jpg", img)
cv2.imshow("JPG", img)
cv2.waitKey(0)
cv2.destroyAllWindows()
'''

'\ncv2.imwrite("wtf.jpg", img)\ncv2.imshow("JPG", img)\ncv2.waitKey(0)\ncv2.destroyAllWindows()\n'

Some references about to coordinates (note how the order of the channels is BGR and not RGB):

In [4]:
b,g,r = img[0, 0]
print(b,g,r)

255 255 255


In [5]:
#let's change some pixels:
import numpy as np
black = np.repeat((0, 0, 0), 100*100).reshape(100, 100, 3)
print(black)
print(black.shape)
img[0:100, 0:100] = black
cv2.imshow("blackened", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
(100, 100, 3)


In [6]:
#A more clever way:
img[0:100, 0:100] = (255, 0, 0)
cv2.imshow("imblue", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Drawing on images

In [7]:
#Drawing a black square
img = np.zeros((500, 500, 3), dtype="uint8") #it is always better to specify the data type

cv2.imshow("blacksquare", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
#Drawing a line on such square
green = (0, 255, 0)

cv2.line(img, (200, 200), (400, 400), green, 4)
cv2.imshow("greenline", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
#Drawing a rectangle
img = np.zeros((500, 500, 3), dtype="uint8") #it is always better to specify the data type

cv2.rectangle(img, (200, 200), (300, 300), (128, 128, 128), 4)
cv2.imshow("greyrec", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
#Drawing a circle
img = np.zeros((500, 500, 3), dtype="uint8") #it is always better to specify the data type

cv2.circle(img, (200, 200), 30, (0, 0, 255), -1)    #-1 in thickness fills the shape with the chosen colour
cv2.circle(img, (img.shape[0]//2, img.shape[1]//2), 100, (255, 255, 255), 1)    #pixel coordinates must be integers
cv2.imshow("whitecircle", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Placholder title

It is possible to split the channels, store them separately and work on them separately.

In [11]:
img = cv2.imread("samples/landscape.jpeg")
b, g, r = cv2.split(img)
reconstruct = cv2.merge((b, g ,r))

cv2.imshow("Red channel", r)    #note how this actually gives only a single channel, and thus a greyscale image
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
#An alternative approach

cv2.imshow("Red channel", img[:, :, 2])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
#Some manipulation

img[:, :, 0:2] = 0
cv2.imshow("Red channel", img)
cv2.waitKey(0)
cv2.destroyAllWindows()