# Numpy introduction

## Numpy arrays

There are multiple ways of creating numpy arrays:
- from a list
- from scratch

In [3]:
import numpy as np

mylist = [1,2,3,4]
np_list = np.array(mylist)
alt_np_list = np.array([2,3,4,5])

print(mylist)
print(np_list)
print(alt_np_list)


[1, 2, 3, 4]
[1 2 3 4]
[2 3 4 5]


In NumPy arrays, all data must be of the same type. If we try to mix types, some will get upcast (for example, integer get upcast to floats):

In [6]:
import numpy as np

mylist = [1.1,2,3,4]
np_list = np.array(mylist)

print(mylist)
print(np_list)


[1.1, 2, 3, 4]
[1.1 2.  3.  4. ]


It is also possible to explicitly declarate the type:

In [8]:
typeList = np.array([1, 2, 3, 4], dtype="int8") #note that these are without sign
print(typeList)

[1 2 3 4]


We can create multidimensional arrays (and note the list comprehension syntax):

In [18]:
np_list = np.array([i for i in [2, 3, 6]])
print(np_list)

[2 3 6]


In [14]:
#A list of zeros and ones

zeros = np.zeros(10, dtype="int8")
ones = np.ones((2, 3, 6), dtype="int8")
print(zeros)
print(ones)

[0 0 0 0 0 0 0 0 0 0]
[[[1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]]

 [[1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]]]


In [16]:
#a list full of a single value
mylist = np.full((2, 3, 3), 3)
print(mylist)

[[[3 3 3]
  [3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]]]


In [19]:
#this works exactly like python
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
#this splits the range into even parts
mylist = np.linspace(0, 1, 5)
print(mylist)

[0.   0.25 0.5  0.75 1.  ]


NumPy supports also various kind of randomness. For example, you can choose numbers according to certain distributions.

In [21]:
mylist = np.random.random(3)
print(mylist)

[0.04266537 0.12790076 0.47914864]


In [22]:
mylist = np.random.normal(0, 2, (2, 2, 2))
print(mylist)

[[[ 0.30515799  0.59856269]
  [ 1.81947156 -0.41854077]]

 [[ 3.97876806  1.58425435]
  [-0.03867719 -1.42806216]]]


In [27]:
mylist = np.random.randint(0, 10, 5)
print(mylist)

[6 6 4 2 1]


NumPy has also some shortcuts to create notable matrices.

In [28]:
#Identity
mylist = np.eye(5)
print(mylist)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [30]:
#Undeclared matrix: values are whatever is found in memory
mylist = np.empty(3)
print(mylist)

[0.04266537 0.12790076 0.47914864]


Each NumPy array has 4 important values:
* number of dimensions (`ndim`)
* elements in each dimension (`shape`)
* total number of entries (`size`)
* type of the array (`dytpe`)

In [33]:
img = np.random.randint(0, 10, (3,5,3))

print(img)
print("array dimensions: ")
print(img.ndim)
print(img.shape)
print(img.size)
print(img.dtype)

[[[0 9 5]
  [1 6 4]
  [1 9 6]
  [5 1 6]
  [7 4 2]]

 [[3 8 2]
  [1 7 2]
  [7 1 7]
  [8 5 8]
  [8 1 9]]

 [[2 2 2]
  [0 0 5]
  [5 3 6]
  [8 7 5]
  [8 4 8]]]
array dimensions: 
3
(3, 5, 3)
45
int64


Indexing is slightly different from standard Python (but is still supports negative indices):

In [35]:
img[1, 2, 2]

7

Every time an array is printed, or assigned to a new variable, we are actually printing a **view** of the array.  
The original array is not changed, but neither a copy is created.  
Every change in the new variable is also applied to the original array.  
An array can be copied with the `copy()` method.

In [42]:
#some practice with subindexing

mylist = np.random.randint(0, 10, (3, 3))
subarray = mylist[:1, 1:2]
print(mylist)
print(subarray)

[[7 8 2]
 [2 9 4]
 [4 8 2]]
[[8]]


In [44]:
col = mylist[:, 2]  #this is an entire column, the third
print(col)
row = mylist[0, :], #this is an entire row, the first
print(row)

[2 4 2]
(array([7, 8, 2]),)
